version: '3'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    command: celery worker -A config.celery -b {{ SPLEEN }} --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
