# PICK UP:
# - sync library source onto infrastructure.qiime2.org: its probably better to just run a `git pull`
# - tweak the playbook so that it runs docker compose correctly
# - set up new UFW rules role
# - done?

- name: sync source
  git:
    repo: https://github.com/qiime2/library
    dest: /home/ubuntu/library-src
    version: master
    update: yes

- name: start celery and rmq containers
  become: True
  command: docker-compose -f /home/ubuntu/library-src/docker-compose.yml up -d
  register: dc
  # TODO: update
  changed_when: '"Creating concourse_db_1" in dc.stderr and "Creating concourse_web_1" in dc.stderr'
