# PICK UP:
# - sync library source onto infrastructure.qiime2.org: its probably better to just run a `git pull`
# - tweak the playbook so that it runs docker compose correctly
# - set up new UFW rules role
# - done?
- name: copy celery docker compose template and Dockerfile
  copy:
    src: .
    dest: "/home/ubuntu"
  # with_items:
  #   - docker-compose.yml
  #   - Dockerfile

- name: start celery and rmq containers
  become: True
  command: docker-compose -f /home/ubuntu/docker-compose.yml up -d
  register: dc
  # TODO: update
  changed_when: '"Creating concourse_db_1" in dc.stderr and "Creating concourse_web_1" in dc.stderr'
