- name: copy celery docker compose template and Dockerfile
  template:
    src: "{{ item }}"
    dest: "/home/ubuntu"
  with_items:
    - docker-compose.yml
    - Dockerfile

- name: start atc and pg containers
  become: True
  command: docker-compose -f $HOME/docker-compose.yml up -d
  register: dc
  # TODO: update
  changed_when: '"Creating concourse_db_1" in dc.stderr and "Creating concourse_web_1" in dc.stderr'
